# Generated by Django 4.2.15 on 2024-09-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeekTide_App', '0002_rename_created_on_post_published_at_remove_post_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
